<?php
session_start();if(!isset($_SESSION['csrf']))$_SESSION['csrf']=bin2hex(random_bytes(32));
header('Cache-Control: no-store');header('X-Content-Type-Options: nosniff');
?>
<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="csrf-token" content="<?=htmlspecialchars($_SESSION['csrf'])?>"><title>QQuantum.ai — .si Domain Observatory</title><meta name="description" content="A QQuantum.ai shortlist of words, service names, personal names, and domain hacks for .si domains."><link rel="icon" href="assets/favicon.svg"><link rel="stylesheet" href="style.css?v=theme-mix-1"><script src="app.js?v=theme-mix-1" defer></script></head>
<body><main>
<header><a class="logo" href="https://qquantum.ai/" target="_blank" rel="noopener" aria-label="Visit QQuantum.ai"><img src="assets/qquantum-logo.svg" alt="QQuantum.ai" width="190" height="35"></a><span class="brand">DOMAIN OBSERVATORY</span><a class="site-link" href="https://qquantum.ai/" target="_blank" rel="noopener">Visit QQuantum.ai ↗</a><a href="DOMAINS.md" download class="download">↓ Download Markdown</a></header>
<section class="intro"><div><p class="eyebrow">A NAME FOR WHAT COMES NEXT</p><h1>Small suffix.<br><em>Super possibilities.</em></h1><p class="lede">Words, coined names, personal names, and domain hacks for your next idea.<br>Explore .si through the lens of super intelligence.</p></div><aside class="intro-note"><span class="pulse"></span><b>Live registrar checks</b><p>Availability from Neoserv and Domenca, with a timestamp on every result. Compare and purchase with Neoserv or Domenca.</p><small>.si is Slovenia’s country-code domain.<br>“Super intelligence” is your branding opportunity.</small></aside></section>
<section class="stats" aria-label="Domain statistics"><div><span id="count-all">—</span><label>Names to explore</label></div><div><span id="count-available" class="green">—</span><label>Available at last check</label></div><div><span id="count-ai">—</span><label>Available AI names</label></div><div><span id="count-bought">—</span><label>Marked bought</label></div></section>
<div class="scanbar"><span id="progress-text" aria-live="polite">Loading shortlist…</span><progress id="progress" max="100" value="0"></progress><button id="check-visible" class="small-button">Recheck this page</button><button id="stop-check" class="small-button" hidden>Stop</button></div>
<section class="catalog"><div class="catalog-head"><div><p class="eyebrow">THE SHORTLIST</p><h2>Find your next name<span>.</span></h2></div><button id="add-toggle" class="small-button">+ Add a name</button></div>
<form id="add-form" hidden><label for="new-name">One word or a .si domain</label><input id="new-name" maxlength="66" placeholder="yourword.si" required><button>Add & check</button></form>
<div class="controls"><label class="search"><span aria-hidden="true">⌕</span><input id="search" placeholder="Search names or ideas…" aria-label="Search names or ideas"></label><select id="category" aria-label="Theme"><option value="">All themes</option></select><select id="sort" aria-label="Sort"><option value="recommended">Recommended first</option><option value="shortest">Shortest first</option><option value="alphabetical">A–Z</option><option value="recent">Recently checked</option></select></div>
<section class="theme-picker" aria-label="Choose themes"><div class="theme-picker-head"><div><span class="theme-heading">Mix your themes</span><span id="theme-selection">Tap buttons to mix your favourites</span></div><label class="counts-toggle"><input type="checkbox" id="show-theme-counts" checked> Show available counts</label></div><div id="theme-buttons" class="theme-buttons" role="group" aria-label="Toggle themes"></div></section>
<div class="filters" aria-label="Filter domains"><button class="active" data-filter="available">Available <span id="tab-available"></span></button><button data-filter="all">All names</button><button data-filter="ai">AI fit</button><button data-filter="favorites">Saved</button><button data-filter="bought">Bought</button><button data-filter="taken">Unavailable</button><button data-filter="unchecked">Unchecked</button><button data-filter="candidate">Needs confirmation</button><button data-filter="unknown">Could not confirm</button><label><input type="checkbox" id="hide-bought"> Hide bought</label></div>
<div class="results-meta"><span id="result-count">—</span><span id="save-message" role="status">Purchase flags save to this folder</span></div>
<div class="table-wrap"><table><thead><tr><th>Name / idea</th><th>Theme</th><th>Availability / checked</th><th>First period</th><th>Purchase</th><th>Bought</th></tr></thead><tbody id="domains"></tbody></table></div><div id="empty" hidden>No names match these filters.</div>
<div class="pagination"><button id="prev">← Previous</button><span id="page-label"></span><button id="next">Next →</button></div></section>
<footer><p class="footer-brand">A domain discovery project by <a href="https://qquantum.ai/" target="_blank" rel="noopener">QQuantum.ai ↗</a>.</p><p><b>Check, then choose.</b> Availability can change until registration completes. A green result is the named registrar’s confirmation at the stated time, not a reservation. The source is shown beside each result. Marking “bought” only updates your tracker.</p><p>Prices in EUR include the VAT returned by the checking registrar; promotions, duration, renewal and final checkout can differ. Dictionary matches use the bundled English word list; established specialist terms are labelled separately. Brand and trademark suitability have not been assessed.</p><div><a href="https://www.register.si/en/rdap/" target="_blank" rel="noopener">Registry methodology ↗</a><a href="https://www.neoserv.si/domene" target="_blank" rel="noopener">Neoserv ↗</a><a href="https://www.domenca.com/domene/" target="_blank" rel="noopener">Domenca ↗</a><a href="README.md" target="_blank">How to use this viewer</a></div></footer>
</main><div id="toast" role="alert" hidden></div></body></html>
