<?php
require dirname(__DIR__).'/lib.php';
$words=[];
foreach(range('a','z') as $a)foreach(range('a','z') as $b)$words[$a.$b]='Two-letter combination; a compact initial-based SI brand.';
$vowels=str_split('aeiou');$consonants=str_split('bcdfghjklmnpqrstvwxyz');
// Two pronounceable shapes, with unusual initials to uncover shorter options.
foreach(str_split('qxz') as $a)foreach($vowels as $b)foreach($consonants as $c){$words[$a.$b.$c]='Three-letter brand candidate; choose a pronunciation that feels natural.';$words[$c.$b.$a]='Three-letter brand candidate; choose a pronunciation that feels natural.';}
foreach($vowels as $a)foreach(str_split('bcdklmnrvstxyz') as $b)foreach($vowels as $c)$words[$a.$b.$c]='A compact vowel-led service name or assistant brand.';
foreach(explode(' ','agi asi sci cog syn psy neu noo bio bot api sdk cli dev app web net hub lab run ops gpu cpu tpu llm rag nlp mlp mcp dag rpc dns ssh ssl tls waf cdn vcs git npm pip sql dba vpc vpn iot iob ioc ide idp sso iam ace act aim air arc ark art ash ava awe axi axo box bud cap cat cue cut day dot duo eco ego era eve evo eye fez fig fit fix flo fly fox fun gem gen geo get gig gox gum hex hip hop hue ice ico ivy jet job joy key kit koa koi lag law lax lea lex lid lin lit lix log lot low lox luc lum lux lyn map max mea met mix mob moa mod moe moo nab neo nex nib nix noa nod nom nor nov now nux oak odd off one orb ore org owl pax pen pep pic pin pip pix pod pop pro pup ram ray red rex rim rio rip rob ron row roy rum rye sag sam sea see set sky sol son sum sun sup tag tao tap tax tea tex tip tom top toy try uni uno use van vec vee vex via vid vim vis vox wax way win wit wok wow wry xen xer xis yap yes yet yin yip zed zen zip zoe zum') as $w)$words[$w]='Three-letter word, name, or acronym candidate for an SI service; suggested fit is a branding idea.';
$added=0;updateStore(function($rows)use($words,&$added){$known=array_fill_keys(array_column($rows,'domain'),true);foreach($words as $w=>$idea){if(isset($known[$w.'.si']))continue;$rows[]=['word'=>$w,'domain'=>$w.'.si','category'=>'2–3 letter names','ai'=>true,'dictionary'=>'Short letter combination / brand candidate','status'=>'unchecked','checked_at'=>null,'bought'=>false,'favorite'=>false,'recommended'=>false,'idea'=>$idea];$added++;}return $rows;});echo "Added $added new short candidates\n";
